apiVersion: v1
kind: Secret
metadata:
  name: github-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/e-espootin/p037-stream-sensor-argocd-kubernetes-datalake.git
  username: argocd
  token: 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