AWS_ACCESS_KEY_ID = "AKIAI4J
AWS_SECRET_ACCESS_KEY = 'a'

hello: hello world
 echo "hello world"

secret:  kubectl create secret generic
 kubectl create secret generic secret --from-literal=aws_access_key_id=$(AWS_ACCESS_KEY_ID) --from-literal=aws_secret_access_key=$(AWS_SECRET_ACCESS_KEY)