apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
      tier: frontend
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
        tier: frontend
    spec: # Pod spec
      containers:
      - name: mycontainer
        image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
        env: # Pass secret values as environment variables
        - name: {{ .Values.secret.AWS_ACCESS_KEY_ID }}
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secret.aws-s3-secret-etlop }}
              key: {{ .Values.secret.AWS_ACCESS_KEY_ID }}
        - name: {{ .Values.secret.AWS_SECRET_ACCESS_KEY }}
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secret.aws-s3-secret-etlop }}
              key: {{ .Values.secret.AWS_SECRET_ACCESS_KEY }}
        ports:
        - containerPort: {{ .Values.port }}
        envFrom:
        - configMapRef:
            name: {{ .Values.configmap.name }}
        resources:
          requests:
            memory: "16Mi" 
            cpu: "50m"    # 50 milli cores (1/20 CPU)
          limits:
            memory: "128Mi" # 128 mebibytes 
            cpu: "100m"